# Generated by Django 4.2.9 on 2024-02-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='account_number',
            new_name='account_no',
        ),
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='birthday_date',
            new_name='birth_date',
        ),
    ]
